platform :ios, '9.0'
use_frameworks!

target 'Speedie' do

	pod 'Alamofire', 		'~> 4.4'
	pod 'RxSwift',    		'~> 3.0'
	pod 'RxCocoa',    		'~> 3.0'
	pod 'ObjectMapper', 	'~> 2.2’
    pod 'IQKeyboardManagerSwift'
    pod 'SwiftyJSON',       '~> 3.0'
    pod 'pop'
    pod 'JVFloatLabeledTextField'
    pod 'kingpin'
    pod 'SwiftDate',        '~> 4.3.0'
    
    pod 'Presentr',         '~> 1.0.0'
    
end

